import AuthWrapper from "@/components/AuthWrapper/AuthWrapper";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body>
          <AuthWrapper>
            {children}
          </AuthWrapper>
        </body>
      </html>
  )
}
